name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build Go project
        run: make build
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*